# Generated by Django 5.2 on 2025-05-13 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgresoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.CharField(choices=[('aire_femenina', 'Aire Femenina'), ('fuego_femenina', 'Fuego Femenina'), ('agua_femenina', 'Agua Femenina'), ('tierra_femenina', 'Tierra Femenina')], max_length=30)),
                ('mision_iniciada', models.BooleanField(default=False)),
                ('mision_inicio_fecha', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
