# Generated by Django 5.1.7 on 2025-04-13 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCrearteConscienteZ', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nivel', models.IntegerField(default=1)),
                ('fuego', models.BooleanField(default=False)),
                ('agua', models.BooleanField(default=False)),
                ('tierra', models.BooleanField(default=False)),
                ('aire', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'appcrearteconscientez_avatar',
            },
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
